apiVersion: v1
kind: Pod
metadata:
  name: fio-tools
spec:
    containers:
    - name: fio-frontend
      image: artmr/fio-serve:0.1
      volumeMounts:
      - name: app-data
        mountPath: /tmp/app-data
    initContainers:
    - name: fio-gen-data
      image: artmr/fio-gen-data:0.1
      env:
        - name: BLOCKSIZE
          valueFrom:
            configMapKeyRef:
              name: fio-tools
              key: gen-data.blocksize
        - name: SIZE
          valueFrom:
            configMapKeyRef:
              name: fio-tools
              key: gen-data.size
        - name: DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: fio-tools
              key: gen-data.directory
        - name: RUNTIME
          valueFrom:
            configMapKeyRef:
              name: fio-tools
              key: gen-data.runtime
        - name: OUTPUT
          valueFrom:
            configMapKeyRef:
              name: fio-tools
              key: gen-data.output
      args: ["/app/job-templates/random-template.fio"]
      volumeMounts:
      - name: benchmarks
        mountPath: /app/benchmarks
      - name: fio-data
        mountPath: /app/data
    - name: fio-gen-plots
      image: artmr/fio-gen-plots:0.1
      args: ["-L", "-i", "/app/benchmarks"]
      volumeMounts:
      - name: benchmarks
        mountPath: /app/benchmarks
      - name: app-data
        mountPath: /app
    volumes:
    - name: fio-data
      persistentVolumeClaim:
        claimName: fio-pv-claim
    - name: benchmarks
      emptyDir: {}
    - name: app-data
      emptyDir: {}

