apiVersion: v1
kind: Service
metadata:
  labels:
    app: fio-tools
  name: fio-tools
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31367
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fio-tools
  type: NodePort
